### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vickris** [Whyounes/laravel-passwordless-auth#1]
Caught a few errors:
- `php artisan vandor:publish` -> vendor
- When adding the trait you should add a backspace before the trait `\use Whyounes\Passwordless\Traits\Passwordless;` since it's not within the app namespace
- Then the view('login.direct') was not created with the `vendor:publish` command

**Comment by Whyounes** [comment]
Thanks, I'll fix those. However, the example section is not meant to work, it's just an example of how it would look like!

**Comment by vickris** [comment]
Cool. Waiting for the official release... 😅
